version: "3"
services:
  app:
    build: .
    restart: on-failure
    ports:
      - 8017:8017
    depends_on:
      - db
      - redis
    volumes:
      #- /home/staticbackup:/code/app/static
      - C:\Users\kerby\Desktop\lingerie\files:/code/app/static

  db:
    image: "mysql:8.0.31"
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=lingerie
      - MYSQL_USER=kerby
      - MYSQL_PASSWORD=123456
      
    volumes:
      - my-datavolume:/var/lib/mysql
      #- mysql_data:/var/lib/mysql
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=
      - REDIS_PORT=6379
      - REDIS_DATABASES=0

volumes:
  #mysql_data: '/home/backups'
  my-datavolume:
    driver: local  # Define the driver and options under the volume name
    driver_opts:
        type: none
        device: C:\Users\kerby\Desktop\lingerie\databack #/mnt/mydatabase
        o: bind
