"""Initial migration

Revision ID: e5ff8acd90c5
Revises: 
Create Date: 2025-03-20 22:19:46.757663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e5ff8acd90c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """
    op.drop_table('media')
    op.drop_table('card_groups')
    op.drop_table('charge_lock')
    op.drop_table('post_collection')
    op.drop_table('notice')
    op.drop_table('cards')
    op.drop_table('vip_user')
    op.drop_table('users')
    op.drop_table('temp_uploaded_files')
    op.drop_table('notice_position')
    op.drop_table('app_setting')
    op.drop_table('post_likes')
    op.drop_index('view_index', table_name='post_views')
    op.drop_table('post_views')
    op.drop_table('feed_back')
    op.drop_table('post_statistic')
    # ### end Alembic commands ###
    
    """
    #op.add_column('app_setting', sa.Column('extra_info', sa.String()))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('app_setting', sa.Column('extra_info', sa.String()))
    """
    op.create_table('post_statistic',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('like_cnt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('collection_cnt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('view_cnt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_statistic_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('feed_back',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1000), nullable=False),
    sa.Column('files', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post_views',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_views_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('view_index', 'post_views', ['user_id', 'post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_likes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('app_setting',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('setting_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('setting_value', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('options', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('last_update_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notice_position',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postion_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=True),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notice.id'], name='notice_position_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('temp_uploaded_files',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('open_id', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('avatar', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('is_admin', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vip_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('open_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='vip_user_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('cards',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_at', mysql.DATETIME(), nullable=True),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['card_groups.id'], name='cards_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='cards_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('notice',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=3000), nullable=False),
    sa.Column('enabled', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('end_time', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pictures', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('post_collection',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_collection_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_collection_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('charge_lock',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cnt', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('card_groups',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('media',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('is_video', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='media_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    """
    # ### end Alembic commands ###
